name: Docker Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: docker.io
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/${{ github.event.repository.name }}

jobs:
  Linux:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Print environment info
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "Docker Image Name: ${{ env.IMAGE_NAME }}"
          echo "Docker Hub User: ${{ env.DOCKER_HUB_USER }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          # 修正：使用完整的 ${{ env.VARIABLE }} 语法
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
